apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: tango-app
  namespace: p-auth-core
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  interval: 5m0s
  url: https://github.com/loft-demos/tango-app.git
  ref:
    branch: main
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-dispatch
  namespace: p-auth-core
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: githubdispatch
  address: https://github.com/loft-demos/tango-app
  secretRef:
    name: loft-demos-pat
---
